### ISSUE TITLE
Rust implementation?

### ISSUE THREAD

**Issue by ghost** [pjebs/optimus-go#5]
I'm interested in leveraging something like this in both Go (static site generator) and Rust (proxy server) to obfuscate Web-bound data. Are you aware of a Rust implementation of this algo? Thanks in advance.

**Comment by pjebs** [comment]
I'm not aware but it wouldn't be hard to do. If you want to do it, I ca link to your implementation.

**Comment by ghost** [comment]
https://git.habd.as/comfusion/webminerpool

**Comment by pjebs** [comment]
?

**Comment by ghost** [comment]
Sorry, I misread your message. Thanks, appreciate it. Will try and loop back as the work comes together if moving this direction.
