### ISSUE TITLE
Local prime generation

### ISSUE THREAD

**Issue by MarcelWaldvogel** [pjebs/optimus-go#6]
You mention trust in the UTM (or any other) prime list as a possible security problem, which I understand.

According to my experiments, it only takes a few seconds to locally compute the first 50+ million primes. (3.5 s using @hacatu's [C implementation of an prime sieve with wheel size 210](https://github.com/hacatu/Prime-Sieve), 7.5 s using a [straightforward Dart port of the same](https://github.com/MarcelWaldvogel/Prime-Sieve-Dart)).

I would expect a Go implementation to be in the same ballpark. You might consider changing to that. The few seconds for the one-off computation will not be a setback.

**Comment by MarcelWaldvogel** [comment]
(At first, I was considering including hashes of the [UTM ZIP files](https://primes.utm.edu/lists/small/millions/) into the source code (as well as changing the URLs to `https`). However, after learning that computing them locally takes only a few seconds, I dropped that plan.)

**Comment by MarcelWaldvogel** [comment]
This would also address the problems mentioned in #4 (package size, dependencies, parsing).

**Comment by pjebs** [comment]
Are you aware of an algorithm that could create cryptically secure random prime?

**Comment by pjebs** [comment]
I have a solution which I will implement tomr.

**Comment by MarcelWaldvogel** [comment]
> Are you aware of an algorithm that could create cryptically secure random prime?

Depends on your security requirements. If breaking/guessing the prime results in significant risks, I would revert to creating primes >= 1024 or 2048 bits, e.g. using [`primegen.c` from the GnuPG library](https://dev.gnupg.org/source/libgcrypt/browse/master/cipher/primegen.c). The file is almost 2000 LoC, even though you probably would only need about half of it for general use.

(Even if we have a large prime; using it to [encrypt a small, guessable number may not be secure](https://asecuritysite.com/encryption/crackrsa2) and will even reveal the prime, as the discrete logarithm problem is simplified to a 'normal' logarithm.)

If primes of roughly in 1E8…1E9 are sufficient (there are ~45 Million 9-digit primes), then they can be enumerated in a few seconds and a random representative chosen. This is as secure as 9-digit primes go.

I believe that given some Optimus-encoded values created from consecutive numbers helps reverse the prime. If the input values are small, it is trivial.

**Comment by pjebs** [comment]
I updated repo with instructions to obtain prime numbers from "somewhere" (deliberately vague).

**Comment by pjebs** [comment]
Thank you for your feedback.
