### ISSUE TITLE
decode back failed

### ISSUE THREAD

**Issue by jiahao1001** [pjebs/optimus-go#7]
```golang	
o1 := optimus.New(1580030173, 59260789, 1163945558)
fmt.Println(o1.Decode(o1.Encode(20210302123)))
```
got 882949291 back, not 20210302123

**Comment by pjebs** [comment]
I can see that `20210302123` is too big.

You can't exceed `MAX_INT = uint64(math.MaxInt32) // 2,147,483,647`.

Try setting `MAX_INT` to a larger number.
