### ISSUE TITLE
Optimus for internal hashes?

### ISSUE THREAD

**Issue by mar1n3r0** [pjebs/optimus-go#8]
Is there something like Optimus which can obfuscate internal hashes transforming them to integers?

**Comment by pjebs** [comment]
What does your internal data look like?

**Comment by mar1n3r0** [comment]
For example: `12D3KooWEGeZ19Q79NdzS6CJBoCwFZwujqi5hoK8BtRcLa48fJdu`.

It is the SHA-256 [multihash](https://github.com/multiformats/multihash) of a public key.

The public key is a base64 encoded string.

Ideally I would like to obfuscate them to non-unique integers like incremental numbers.

**Comment by pjebs** [comment]
Do you need to reverse the process to get the original back?

**Comment by mar1n3r0** [comment]
Yes. I need to be able to convert back and forth.

**Comment by pjebs** [comment]
So you want to convert the hash into an integer.
A 64-bit integer only has a range of 2^64 combinations. I don't think there is anyway for SHA-256 hash to fit within that combination space, in such a way that it can unambiguously be converted back.

**Comment by mar1n3r0** [comment]
I was hoping that I can rather map it say to 1 and then convert back with the help of the 3 numbers that are used in the process. Maybe not the same algorithm but something that can do that.

**Comment by pjebs** [comment]
I don't think it would be possible to convert it to an integer.
However, there might be a way to convert it to a string that _contains_ a representation of an integer. Then the number can be as long as you want.

I'm pretty sure any of Go's encryption algorithms will work for you. Just make sure you save the string output as a number representation instead of the usual hex.

https://tutorialedge.net/golang/go-encrypt-decrypt-aes-tutorial/
https://www.melvinvivas.com/how-to-encrypt-and-decrypt-data-using-aes

**Comment by pjebs** [comment]
https://go.dev/play/p/mNIftoSvXZ_j (from prior link)

**Comment by mar1n3r0** [comment]
But that's encryption rather than obfuscation isn't it? The code will be open source so the key will be exposed.

In my case I have the input and the desired output I think I just need obfuscation based on randomly generated numbers.

**Comment by pjebs** [comment]
https://go.dev/play/p/uwL6QAp1pEn.  <---- converted to a number

No. You have to keep the key secret just like in Optimus. Don't share they key. In that example, they generate a random key. In your case, you generate it once and then keep it secret.

**Comment by pjebs** [comment]
Optimus:

```

o := optimus.New(1580030173, 59260789, 1163945558)  <------- You need to keep a record of this in order to transform and convert back
new_id := o.Encode(15) // internal id of 15 being transformed to 1103647397
orig_id := o.Decode(1103647397) // Returns 15 back
```

**Comment by pjebs** [comment]
Hashing is one way (can't convert back).
Encryption is 2 way. You want 2 way.

**Comment by mar1n3r0** [comment]
Yeah totally get it but also encryption is different than obfuscation isn't it?

> You can use the built-in generator.GenerateSeed() function to generate all 3 required parameters if you want.

I was hoping I can seed the numbers per client rather than using the same and storing them.

I need control over the output number. For example - map `12D3KooWEGeZ19Q79NdzS6CJBoCwFZwujqi5hoK8BtRcLa48fJdu` to `1` and give me a way to convert back.

**Comment by pjebs** [comment]
`generator.GenerateSeed()` just generates 3 random numbers. If you want to do it per client, you will need to store those 3 random numbers per client.

In the encryption example above, you will need to create the random key per client too.

**Comment by pjebs** [comment]
Obfuscation just means hiding the number so it's not immediately obvious what the original number is.
Encryption by definition is also a form of obfuscation.

**Comment by mar1n3r0** [comment]
Thanks, I understand. Persisting a key is a no-go in my scenario so I have to think more what my options are.
